USE DDOC;

CREATE TABLE DDOC_BLOB_INFO (
	BLOB_ID VARCHAR(100) PRIMARY KEY,
	FILE_BLOB LONGBLOB,
	FILE_SIZE VARCHAR(100),
	REG_TIME VARCHAR(20),
	ORIGIN_FILE_NAME VARCHAR(500),
	ORIGIN_FILE_PATH VARCHAR(4000),
	CACHE_FILE_NAME VARCHAR(500),
	CACHE_FILE_PATH VARCHAR(4000),
	IS_DELETE VARCHAR(1),
	IS_POST VARCHAR(1));
    
CREATE TABLE TEST_MEMBER (
    ID VARCHAR(255) PRIMARY KEY NOT NULL,
    NAME VARCHAR(255),
    AGE INTEGER);