USE DDOC;


CREATE TABLE DDOC_BLOB_INFO (
	BLOB_ID VARCHAR(100) PRIMARY KEY,
	FILE_BLOB LONGBLOB,
	FILE_SIZE VARCHAR(100),
	REG_TIME VARCHAR(20),
	ORIGIN_FILE_NAME VARCHAR(500),
	ORIGIN_FILE_PATH VARCHAR(4000),
	CACHE_FILE_NAME VARCHAR(500),
	CACHE_FILE_PATH VARCHAR(4000),
	IS_DELETE VARCHAR(1),
	IS_POST VARCHAR(1));

	
CREATE TABLE TEST_MEMBER (
    ID VARCHAR(255) PRIMARY KEY NOT NULL,
    NAME VARCHAR(255),
    AGE INTEGER);

    
CREATE TABLE DDOC_MEMBER (
	USER_ID VARCHAR(100) PRIMARY KEY,
	USER_NAME VARCHAR(100),
	PASSWORD VARCHAR(500),
	REG_TIME VARCHAR(20),
	DEL_TIME VARCHAR(20),
	BEGIN_TIME VARCHAR(20),
	END_TIME VARCHAR(20),
	IS_VALID VARCHAR(1)
);


CREATE TABLE DDOC_DOC_LIST (
	 SEQ_NUM VARCHAR(32),
	 DOC_ID VARCHAR(32) PRIMARY KEY,
	 USER_ID VARCHAR(20),
	 USER_NAME VARCHAR(20),
	 TITLE VARCHAR(1000),
	 CONTENT MEDIUMTEXT,
	 CONTENT_SRC VARCHAR(200),
	 IP_ADDRESS VARCHAR(100),
	 VALID CHAR(1),
	 REGIST_TIME VARCHAR(14),
	 UPDATE_TIME VARCHAR(14),
	 BOOK_ID VARCHAR(32),
	 SECRET CHAR(2)
);


CREATE INDEX IDX_DDOC_DOC_LIST ON DDOC_DOC_LIST (REGIST_TIME, BOOK_ID);